name: CCcam Auto Update

on:
  schedule:
    - cron: '0 */3 * * *' # تحديث كل 3 ساعات
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Dependencies
        run: pip install requests
      - name: Run
        run: python scraper.py
      - name: Push Changes
        run: |
          git config --global user.name "Badr-cx"
          git config --global user.email "badr-cx@users.noreply.github.com"
          git add CCcam.cfg
          git commit -m "Update CCcam.cfg - $(date)" || echo "No changes"
          git push
