name: CCcam Elite Hunter

on:
  schedule:
    - cron: '0 */4 * * *' # Ø§Ù„Ø³ÙƒØ±Ø¨Øª ÙƒÙŠØ®Ø¯Ù… Ù„Ø±Ø§Ø³Ùˆ ÙƒÙ„ 4 Ø³ÙˆØ§ÙŠØ¹
  workflow_dispatch:      # ÙƒÙŠØ®Ù„ÙŠÙƒ ØªØ®Ø¯Ù…Ùˆ Ø¨ÙŠØ¯ÙŠÙƒ (Run workflow) Ù…Ù† GitHub
  push:
    branches:
      - main              # ÙƒÙŠØ®Ø¯Ù… Ù…Ù„ÙŠ ÙƒØªØ¨Ø¯Ù„ Ø´ÙŠ Ø­Ø§Ø¬Ø© ÙÙŠ Ø§Ù„ÙƒÙˆØ¯

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Clean Old Files
      run: |
        rm -f VERIFIED_CANNON.cfg
        echo "Old file deleted successfully."

    - name: Run Scraper
      run: python scraper.py

    - name: Commit and Push
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add VERIFIED_CANNON.cfg
        # Ù‡Ø§Ø¯ Ø§Ù„Ø³Ø·Ø± ÙƒÙŠÙ…Ù†Ø¹ Ø§Ù„Ø³ÙƒØ±Ø¨Øª ÙŠØ­Ø¨Ø³ Ø¥Ù„Ø§ Ù…Ø§Ù„Ù‚Ø§Ø´ ØªØºÙŠÙŠØ±Ø§Øª
        git commit -m "ğŸš€ Update: New Elite Servers $(date +'%Y-%m-%d %H:%M')" || exit 0
        git push
